### ISSUE TITLE
Infra

### ISSUE THREAD

**Issue by gigafiga21** [gigafiga21/bearing-only-tracking#3]
Add project infrastructure

### ToDo
- [x] github commit name linting
- [x] github branch namings linting
- [x] python dependences manager
